In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
file = '../data/train.json'
out_file = '../data/train_processed.csv'

In [15]:
df = pd.read_json(file)
df

                                                   text     id sentiment
0     Досудебное расследование по факту покупки ЕНПФ...   1945  negative
1     Медики рассказали о состоянии пострадавшего му...   1957  negative
2     Прошел почти год, как железнодорожным оператор...   1969  negative
3     По итогам 12 месяцев 2016 года на территории р...   1973  negative
4     Астана. 21 ноября. Kazakhstan Today - Агентств...   1975  negative
...                                                 ...    ...       ...
8258  Как мы писали еще весной, для увеличения сбыта...  10312  positive
8259  Но молодой министр национальной экономики Биши...  10313  negative
8260  \n \nВ ЕНПФ назначен новый председатель правле...  10314   neutral
8261  В Алматы у отделения банка произошло нападение...  10315  negative
8262  НПП РК «Атамекен» предлагает создать Националь...  10316   neutral

[8263 rows x 3 columns]

In [16]:
#  Определим количество данных в каждом классе
df['sentiment'].value_counts()

neutral     4034
positive    2795
negative    1434
Name: sentiment, dtype: int64

In [ ]:
# Упс, выборка не сбалансированная. Придется убрать лишнее

In [21]:
# Выберем отдельно позитивные, негативные и нейтральные новости
keys = df['sentiment'].unique()
data = {}
for key in keys:
    data[key] = df[df['sentiment'] == key]

In [23]:
# Перемешаем
for key in keys:
    data[key] = data[key].sample(frac=1).reset_index(drop=True)

In [26]:
# Обрежем по самому короткому
min_len = min(len(d) for d in data.values())
print('Min length:',min_len)

for key in keys:
    data[key] = data[key][:min_len]

Min length: 1434

In [33]:
# Соберем обратно
df = pd.concat(data.values())
df

                                                   text    id sentiment
0      Инвалид-колясочник погиб в подземном переходе...  3634  negative
1     \n\nЖенщина требовала встречи с генеральным пр...  5139  negative
2     МОСКВА (S&P Global Ratings), 21 декабря 2016 г...  5818  negative
3     В частности, речь идет коммунально-бытовых сто...  6041  negative
4     Один из главных постулатов казахстанской прогр...  9107  negative
...                                                 ...   ...       ...
1429  Возобновлено движение пассажирских поездов на ...  4331   neutral
1430  Современные технология нам помогут. Казахстан ...  3340   neutral
1431  Национальный банк Казахстана установил официал...  4754   neutral
1432  10.01.2017, 12:14\nРост ВВП Казахстана по итог...  6179   neutral
1433  Уральск. 30 декабря. Kazakhstan Today - С 1 ян...  3053   neutral

[4302 rows x 3 columns]

In [42]:
df.to_csv(out_file, index=False)

In [43]:
df1 = pd.read_csv(out_file)
df1

                                                   text    id sentiment
0      Инвалид-колясочник погиб в подземном переходе...  3634  negative
1     \n\nЖенщина требовала встречи с генеральным пр...  5139  negative
2     МОСКВА (S&P Global Ratings), 21 декабря 2016 г...  5818  negative
3     В частности, речь идет коммунально-бытовых сто...  6041  negative
4     Один из главных постулатов казахстанской прогр...  9107  negative
...                                                 ...   ...       ...
4297  Возобновлено движение пассажирских поездов на ...  4331   neutral
4298  Современные технология нам помогут. Казахстан ...  3340   neutral
4299  Национальный банк Казахстана установил официал...  4754   neutral
4300  10.01.2017, 12:14\nРост ВВП Казахстана по итог...  6179   neutral
4301  Уральск. 30 декабря. Kazakhstan Today - С 1 ян...  3053   neutral

[4302 rows x 3 columns]